### PR TITLE
FCBH-2384 Add user data to downloads

### PR DESCRIPTION
**Pull request by JramR7**
# Description
* Create a migration for userDownloads with id, user_id, fileset_id, and created_at 
* Create model for userDownloads with foreign keys for user, fileset and book
* Add userDownloads on bible controller, creating the model when there's a user and there's a drama/non_drama fileset
* use cache to save user  downloads

## Issue Link
[FCBH-2384](https://fullstacklabs.atlassian.net/browse/FCBH-2384) 

## How Do I QA This
- Run migrations and check the user_download table was created
- Test `/bibles/{bible_id}` `GET` endpoint (You must have an api_token, use zip true, add chapter and book id, and assign drama keys)
- Check the if the user_download row was created with the correct data

## Checklist

- [] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed locally.

### CODE REVIEW

**Review by jrstear — CHANGES_REQUESTED** [review]
please do not save book or chapter, which are unnecessary

**Comment by jrstear** [comment]
please add @bradflood  as a reviewer of DBP PR's instead of me going forward, thank you!

**Review by mgonzalezs — APPROVED** [review]

**Review by jrstear — APPROVED** [review]
thanks for the changes!

**Review by bradflood — APPROVED** [review]

**Comment by jrstear** [comment]
@bradflood this provides opportunties regarding migrations.  eg, 1) what happens to dev api and alpha app while this code is deployed on dev server but the corresponding migration has not been done?  2) what process would you like to establish for coordinating when migrations occur, keeping track of when they must occur on prod, etc?

**Comment by jrstear** [comment]
also @bradflood , once migrations are cleaned up, you could consider changing env user/password to enable auto-application of migrations as part of auto-deployment.  just an idea to consider.

**Pull request merged**
